
<header class="Head">
  <h1>Start your journey</h1>
	<form method="get" action="index.php" style="width:70%; margin:auto; padding:5px;">
	<table style="margin:auto; border:hidden;">
	<tr>
      <td style="border:hidden;">
          <input type="text" placeholder="Search.." name="search" size="50"
                 value="" style="padding:15px; width=100%;"></td>
      <td style="border:hidden;">
          <button type="submit" ><img src= "image/Search.png"
                                      height="30px" width="30px"></button></td>
    </tr>
    </table>
    </form>
</header>