
<header class="Head">
  <h1>Train tracker</h1>
	<form method="get" action="index.php" style="width:70%; margin:auto; padding:5px;">
	<table style="margin:auto; border:hidden;">
	<tr>
      <td style="border:hidden;"><input type="text" placeholder="Search.." name="search" size="50" value="" style="padding:10px; width=100%;"></td>
      <td style="border:hidden;"><button type="submit" ><img src= "image/Search.png" height="40px" width="40px"></button></td>
    </tr>
    </table>
    </form>
</header>