<!doctype html>
<html>
<head>
<link type="text/css" rel="stylesheet" href="style.css"/>
<meta charset="utf-8">
</head>
<header>
  <div class="Head">
  <h1>Train tracker</h1>
  <div class="search-container">
	<form action="index.php">
      <input type="text" placeholder="Search.." name="search" style="padding: 10px;">
      <button type="submit" ><img src= "search.png" height="50px" width="50px" style="float:right"></button>
    </form>
  </div>
  </div>
</header>
