<!doctype html>
<html>
<head>
    <link type="text/css" rel="stylesheet" href="css/style.css"/>
    <meta charset="utf-8">
</head>

<nav>
 <div>
  <ul>
      <li><a href="index.php"><img src= "image/SignIn.png" height="40px" width="40px">My account</a></li>
      <li><a href="index.php"><img src= "image/star.png" height="40px" width="40px">Favourite</a></li>
      <li><a href="index.php">HOME</a></li>
      </ul>
</div>
</nav>